language: java
after_success:
- mvn deploy
before_install:
- openssl aes-256-cbc -K $encrypted_9a895d496368_key -iv $encrypted_9a895d496368_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
notifications:
  email:
    - arena-uqbar@googlegroups.com

